# Generated by Django 3.0.4 on 2020-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='table_name',
            field=models.CharField(default='table', max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='uploaded_files'),
        ),
    ]
